/*
 * @description: 组合报表所需数据
 * @author: huxianghe
 * @lastEditors: huxianghe
 * @Date: 2019-04-28 10:29:10
 * @LastEditTime: 2020-06-03 13:50:56
 * @copyright: Copyright © 2019 Shanghai Yejia Digital Technology Co., Ltd. All rights reserved.
 */
import * as React from 'react'

const toFixed = (n: string) => {
  if (!n) return '- - -'
  return parseFloat(n).toFixed(2)
}

// 报表模板数据列表
const reportFormTemplateList = [
  { id: 1, alias: 'rosterColumns', name: '花名册汇总表' },
  { id: 2, alias: 'workingColumns', name: '在职名单汇总表' },
  { id: 3, alias: 'quitColumns', name: '离职名单汇总表' },
  { id: 4, alias: 'probationPeriod', name: '试用期审核名单汇总表' },
  { id: 5, alias: 'contractEndColumns', name: '合同到期名单汇总表' },
  { id: 6, alias: 'contractInfoColumns', name: '合同信息汇总表' },
  { id: 7, alias: 'jobChangeColumns', name: '异动信息汇总表' },
  { id: 8, alias: 'insuredDetailColumns', name: '参保明细汇总表' }
  // { id: 9, alias: 'insuredCostColumns', name: '参保费用拆分汇总表' },
  // { id: 10, alias: 'insuredPayColumns', name: '参保费用付款汇总表' }
]

/* ********************* 十种表格表头数据 ********************* */

// 01-花名册汇总表
const rosterColumns = [
  { title: '', dataIndex: 'index' },
  { title: '项目', dataIndex: 'projectName', width: 30 },
  { title: '工号', dataIndex: 'projectNumber', width: 60 },
  { title: '管理编号', dataIndex: 'sjNumber', width: 60 },
  { title: '组织', dataIndex: 'organize', width: 30 },
  { title: '在职状态', dataIndex: 'workCondition', width: 60 },
  { title: '入职日期', dataIndex: 'entryTime', width: 60 },
  { title: '离职日期', dataIndex: 'quitTime', width: 60 },
  { title: '服务期限', dataIndex: 'serviceTime', width: 60 },
  { title: '姓名', dataIndex: 'userName', width: 30 },
  { title: '性别', dataIndex: 'sex', width: 30 },
  { title: '年龄', dataIndex: 'age', width: 30 },
  { title: '身份证号码/通行证/护照号', dataIndex: 'idCard', render: (text:string, recode:any) => (<span>{text || recode.passportCard || '- - -'}</span>) },
  { title: '护照号码', dataIndex: 'passportCard', width: 60 },
  { title: '出生日期', dataIndex: 'birth', width: 60 },
  { title: '民族', dataIndex: 'nation', width: 30 },
  { title: '籍贯', dataIndex: 'nativePlace', width: 30 },
  { title: '国家', dataIndex: 'country', width: 30 },
  { title: '婚姻状况', dataIndex: 'maritalStatus', width: 60 },
  { title: '最高学历', dataIndex: 'maxEducation', width: 60 },
  { title: '银行卡号', dataIndex: 'bankCard', width: 60 },
  { title: '户口地址', dataIndex: 'residenceAdress', width: 60 },
  { title: '户口性质', dataIndex: 'residenceNature', width: 60 },
  { title: '联系地址', dataIndex: 'contactAdress', width: 60 },
  { title: '联系方式', dataIndex: 'contactWay', width: 60 },
  { title: '紧急联系人', dataIndex: 'urgentUser', width: 80 },
  { title: '紧急联系人关系', dataIndex: 'urgentRelation', width: 100 },
  { title: '紧急联系人电话', dataIndex: 'urgentPhone', width: 100 },
  { title: '工时类型', dataIndex: 'hourType', width: 60 },
  { title: '计税类型', dataIndex: 'taxationType', width: 60 },
  { title: '合同起始日期', dataIndex: 'startTime', width: 90 },
  { title: '合同终止日期', dataIndex: 'endTime', width: 90 },
  { title: '试用期结束日期', dataIndex: 'tryEndTime', width: 100 },
  { title: '试用期基本工资', dataIndex: 'probationBaseSalary', width: 100, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '试用期绩效工资', dataIndex: 'probationPerSalary', width: 100, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '等级', dataIndex: 'grade', width: 30 },
  { title: '档级', dataIndex: 'files', width: 30 },
  { title: '层级', dataIndex: 'level', width: 30 },
  { title: '基本工资', dataIndex: 'baseSalary', width: 60, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '绩效工资', dataIndex: 'performanceSalary', width: 60, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '层级工资', dataIndex: 'hierarchySalary', width: 60, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '绩效奖金', dataIndex: 'performanceBonus', width: 60, render: (text: string) => (<span>{toFixed(text)}</span>) }
]

// 02-在职名单汇总表
const workingColumns = [
  { title: '', dataIndex: 'index', width: 50 },
  { title: '项目', dataIndex: 'projectName', width: 50 },
  { title: '工号', dataIndex: 'projectNumber', width: 100 },
  { title: '管理编号', dataIndex: 'sjNumber', width: 100 },
  { title: '组织', dataIndex: 'organize', width: 100 },
  { title: '在职状态', dataIndex: 'workCondition', width: 50 },
  { title: '入职日期', dataIndex: 'entryTime', width: 100 },
  { title: '离职日期', dataIndex: 'quitTime', width: 100 },
  { title: '服务期限', dataIndex: 'serviceTime', width: 100 },
  { title: '姓名', dataIndex: 'userName', width: 100 },
  { title: '性别', dataIndex: 'sex', width: 50 },
  { title: '年龄', dataIndex: 'age', width: 50 },
  { title: '身份证号码/通行证/护照号', dataIndex: 'idCard', render: (text:string, recode:any) => (<span>{text || recode.passportCard || '- - -'}</span>) },
  { title: '护照号码', dataIndex: 'passportCard', width: 150 },
  { title: '出生日期', dataIndex: 'birth', width: 100 },
  { title: '民族', dataIndex: 'nation', width: 50 },
  { title: '籍贯', dataIndex: 'nativePlace', width: 50 },
  { title: '国家', dataIndex: 'country', width: 50 },
  { title: '婚姻状况', dataIndex: 'maritalStatus', width: 50 },
  { title: '最高学历', dataIndex: 'maxEducation', width: 50 },
  { title: '银行卡号', dataIndex: 'bankCard', width: 150 },
  { title: '户口地址', dataIndex: 'residenceAdress', width: 150 },
  { title: '户口性质', dataIndex: 'residenceNature', width: 50 },
  { title: '联系地址', dataIndex: 'contactAdress', width: 150 },
  { title: '联系方式', dataIndex: 'contactWay', width: 100 },
  { title: '紧急联系人', dataIndex: 'urgentUser', width: 50 },
  { title: '紧急联系人关系', dataIndex: 'urgentRelation', width: 50 },
  { title: '紧急联系人电话', dataIndex: 'urgentPhone', width: 100 },
  { title: '工时类型', dataIndex: 'hourType', width: 50 },
  { title: '计税类型', dataIndex: 'taxationType', width: 50 },
  { title: '合同起始日期', dataIndex: 'startTime', width: 100 },
  { title: '合同终止日期', dataIndex: 'endTime', width: 100 },
  { title: '试用期结束日期', dataIndex: 'tryEndTime', width: 100 },
  { title: '试用期基本工资', dataIndex: 'probationBaseSalary', width: 100, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '试用期绩效工资', dataIndex: 'probationPerSalary', width: 100, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '等级', dataIndex: 'levelName', width: 50 },
  { title: '基本工资', dataIndex: 'baseSalary', width: 50, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '绩效工资', dataIndex: 'performanceSalary', width: 50, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '层级工资', dataIndex: 'hierarchySalary', width: 50, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '绩效奖金', dataIndex: 'performanceBonus', width: 50, render: (text: string) => (<span>{toFixed(text)}</span>) }
]

// 03-离职名单汇总表
const quitColumns = [
  { title: '', dataIndex: 'index', width: 50 },
  { title: '项目', dataIndex: 'projectName', width: 50 },
  { title: '工号', dataIndex: 'projectNumber', width: 100 },
  { title: '管理编号', dataIndex: 'sjNumber', width: 100 },
  { title: '组织', dataIndex: 'organize', width: 100 },
  { title: '在职状态', dataIndex: 'workCondition', width: 50 },
  { title: '入职日期', dataIndex: 'entryTime', width: 100 },
  { title: '离职日期', dataIndex: 'quitTime', width: 100 },
  { title: '服务期限', dataIndex: 'serviceTime', width: 100 },
  { title: '姓名', dataIndex: 'userName', width: 100 },
  { title: '性别', dataIndex: 'sex', width: 50 },
  { title: '年龄', dataIndex: 'age', width: 50 },
  { title: '身份证号码/通行证/护照号', dataIndex: 'idCard', render: (text:string, recode:any) => (<span>{text || recode.passportCard || '- - -'}</span>) },
  { title: '护照号码', dataIndex: 'passportCard', width: 150 },
  { title: '出生日期', dataIndex: 'birth', width: 100 },
  { title: '民族', dataIndex: 'nation', width: 50 },
  { title: '籍贯', dataIndex: 'nativePlace', width: 50 },
  { title: '国家', dataIndex: 'country', width: 50 },
  { title: '婚姻状况', dataIndex: 'maritalStatus', width: 50 },
  { title: '最高学历', dataIndex: 'maxEducation', width: 50 },
  { title: '银行卡号', dataIndex: 'bankCard', width: 150 },
  { title: '户口地址', dataIndex: 'residenceAdress', width: 150 },
  { title: '户口性质', dataIndex: 'residenceNature', width: 50 },
  { title: '联系地址', dataIndex: 'contactAdress', width: 150 },
  { title: '联系方式', dataIndex: 'contactWay', width: 100 },
  { title: '紧急联系人', dataIndex: 'urgentUser', width: 50 },
  { title: '紧急联系人关系', dataIndex: 'urgentRelation', width: 50 },
  { title: '紧急联系人电话', dataIndex: 'urgentPhone', width: 100 },
  { title: '工时类型', dataIndex: 'hourType', width: 50 },
  { title: '计税类型', dataIndex: 'taxationType', width: 50 },
  { title: '合同起始日期', dataIndex: 'startTime', width: 100 },
  { title: '合同终止日期', dataIndex: 'endTime', width: 100 },
  { title: '试用期结束日期', dataIndex: 'tryEndTime', width: 100 },
  { title: '试用期基本工资', dataIndex: 'probationBaseSalary', width: 100, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '试用期绩效工资', dataIndex: 'probationPerSalary', width: 100, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '等级', dataIndex: 'levelName', width: 50 },
  { title: '基本工资', dataIndex: 'baseSalary', width: 50, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '绩效工资', dataIndex: 'performanceSalary', width: 50, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '层级工资', dataIndex: 'hierarchySalary', width: 50, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '绩效奖金', dataIndex: 'performanceBonus', width: 50, render: (text: string) => (<span>{toFixed(text)}</span>) }
]

// 04-试用期审核名单汇总表
const probationPeriod = [
  { title: '', dataIndex: 'index', width: 50 },
  { title: '项目', dataIndex: 'projectName', width: 50 },
  { title: '工号', dataIndex: 'projectNumber', width: 100 },
  { title: '管理编号', dataIndex: 'sjNumber', width: 100 },
  { title: '组织', dataIndex: 'organize', width: 100 },
  { title: '在职状态', dataIndex: 'workCondition', width: 50 },
  { title: '入职日期', dataIndex: 'entryTime', width: 100 },
  { title: '姓名', dataIndex: 'userName', width: 100 },
  { title: '身份证号码/通行证/护照号', dataIndex: 'idCard', render: (text:string, recode:any) => (<span>{text || recode.passportCard || '- - -'}</span>) },
  { title: '护照号码', dataIndex: 'passportCard', width: 150 },
  { title: '员工类型', dataIndex: 'roleType', width: 100 },
  { title: '合同类型', dataIndex: 'contractType', width: 50 },
  { title: '法人主体', dataIndex: 'mainBody', width: 100 },
  { title: '试用期起始日期', dataIndex: 'probationStart', width: 100 },
  { title: '试用期结束日期', dataIndex: 'probationEnd', width: 100 }
]

// 05-合同到期名单汇总表
const contractEndColumns = [
  { title: '', dataIndex: 'index', width: 50 },
  { title: '项目', dataIndex: 'projectName', width: 50 },
  { title: '工号', dataIndex: 'projectNumber', width: 100 },
  { title: '管理编号', dataIndex: 'sjNumber', width: 100 },
  { title: '组织', dataIndex: 'organize', width: 100 },
  { title: '在职状态', dataIndex: 'workCondition', width: 50 },
  { title: '入职日期', dataIndex: 'entryTime', width: 100 },
  { title: '姓名', dataIndex: 'userName', width: 100 },
  { title: '身份证号码/通行证/护照号', dataIndex: 'idCard', render: (text:string, recode:any) => (<span>{text || recode.passportCard || '- - -'}</span>) },
  { title: '护照号码', dataIndex: 'passportCard', width: 150 },
  { title: '员工类型', dataIndex: 'roleType', width: 100 },
  { title: '合同类型', dataIndex: 'contractType', width: 50 },
  { title: '法人主体', dataIndex: 'mainBody', width: 100 },
  { title: '工时类型', dataIndex: 'manHourType', width: 100 },
  { title: '计税类型', dataIndex: 'taxationType', width: 100 },
  { title: '合同起始日期', dataIndex: 'contractStart', width: 100 },
  { title: '合同终止日期', dataIndex: 'contractEnd', width: 100 },
  { title: '初签/续签', dataIndex: 'baseType', width: 50 }
]

// 06-合同信息汇总表
const contractInfoColumns = [
  { title: '', dataIndex: 'index', width: 50 },
  { title: '项目', dataIndex: 'projectName', width: 50 },
  { title: '工号', dataIndex: 'projectNumber', width: 100 },
  { title: '管理编号', dataIndex: 'sjNumber', width: 100 },
  { title: '组织', dataIndex: 'organize', width: 100 },
  { title: '入职日期', dataIndex: 'entryTime', width: 100 },
  { title: '姓名', dataIndex: 'userName', width: 100 },
  { title: '身份证号码/通行证/护照号', dataIndex: 'idCard', render: (text:string, recode:any) => (<span>{text || recode.passportCard || '- - -'}</span>) },
  { title: '护照号码', dataIndex: 'passportCard', width: 150 },
  { title: '员工类型', dataIndex: 'roleType', width: 100 },
  { title: '合同类型', dataIndex: 'contractType', width: 50 },
  { title: '法人主体', dataIndex: 'mainBody', width: 100 },
  { title: '工时类型', dataIndex: 'manHourType', width: 100 },
  { title: '计税类型', dataIndex: 'taxationType', width: 100 },
  { title: '合同起始日期', dataIndex: 'contractStart', width: 100 },
  { title: '合同终止日期', dataIndex: 'contractEnd', width: 100 },
  { title: '初签/续签', dataIndex: 'baseType', width: 50 }
]

// 07-异动信息汇总表
const jobChangeColumns = [
  { title: '', dataIndex: 'index', width: 50 },
  { title: '项目', dataIndex: 'projectName', width: 50 },
  { title: '工号', dataIndex: 'projectNumber', width: 100 },
  { title: '管理编号', dataIndex: 'sjNumber', width: 100 },
  { title: '姓名', dataIndex: 'userName', width: 100 },
  { title: '入职日期', dataIndex: 'entryTime', width: 100 },
  { title: '离职日期', dataIndex: 'quitTime', width: 100 },
  { title: '异动生效日期', dataIndex: 'transactionDate', width: 100 },
  { title: '状态', dataIndex: 'workCondition', width: 50 },
  { title: '员工类型', dataIndex: 'roleType', width: 50 },
  { title: '异动前-法人主体', dataIndex: 'beforeEntity', width: 150 },
  { title: '异动后-法人主体', dataIndex: 'laterEntity', width: 150 },
  { title: '异动前-组织', dataIndex: 'beforeOrganize', width: 150 },
  { title: '异动后-组织', dataIndex: 'laterOrganize', width: 150 },
  { title: '异动前-等级', dataIndex: 'beforeLevelName', width: 50 },
  { title: '异动后-等级', dataIndex: 'laterLevelName', width: 50 },
  { title: '异动前-档级', dataIndex: 'beforeGradeName', width: 50 },
  { title: '异动后-档级', dataIndex: 'laterGradeName', width: 50 },
  { title: '异动前-层级', dataIndex: 'beforeHierarchyName', width: 50 },
  { title: '异动后-层级', dataIndex: 'laterHierarchyName', width: 50 },
  { title: '异动前-职位', dataIndex: 'beforePosition', width: 50 },
  { title: '异动后-职位', dataIndex: 'laterPosition', width: 50 },
  { title: '异动前-职级', dataIndex: 'beforeRank', width: 50 },
  { title: '异动后-职级', dataIndex: 'laterRank', width: 50 },
  { title: '异动前-序列', dataIndex: 'beforeSequence', width: 50 },
  { title: '异动后-序列', dataIndex: 'laterSequence', width: 50 },
  { title: '异动前-职等', dataIndex: 'beforeOfficialRank', width: 50 },
  { title: '异动后-职等', dataIndex: 'laterOfficialRank', width: 50 },
  { title: '银行卡号', dataIndex: 'bankCard', width: 150 },
  { title: '异动前-基本工资', dataIndex: 'beforeBaseSalary', width: 100, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '异动后-基本工资', dataIndex: 'laterBaseSalary', width: 100, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '异动前-绩效工资', dataIndex: 'beforePerformanceSalary', width: 100, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '异动后-绩效工资', dataIndex: 'laterPerformanceSalary', width: 100, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '异动前-层级工资', dataIndex: 'beforeHierarchySalary', width: 180, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '异动后-层级工资', dataIndex: 'laterHierarchySalary', width: 180, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '异动前-绩效奖金', dataIndex: 'beforePerformanceBonus', width: 180, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '异动后-绩效奖金', dataIndex: 'laterPerformanceBonus', width: 180, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '异动前-试用期基本工资', dataIndex: 'beforeProbationBaseSalary', width: 100, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '异动后-试用期基本工资', dataIndex: 'laterProbationBaseSalary', width: 100, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '异动前-试用期绩效工资', dataIndex: 'beforeProbationPerSalary', width: 100, render: (text: string) => (<span>{toFixed(text)}</span>) },
  { title: '异动后-试用期绩效工资', dataIndex: 'laterProbationPerSalary', width: 100, render: (text: string) => (<span>{toFixed(text)}</span>) }
]

// 08-参保明细汇总表
const insuredDetailColumns = [
  { title: '', dataIndex: 'index', width: 50 },
  { title: '项目', dataIndex: 'projectName', width: 50 },
  { title: '法人主体', dataIndex: 'entity', width: 150 },
  { title: '工号', dataIndex: 'projectNumber', width: 100 },
  { title: '管理编号', dataIndex: 'sjNumber', width: 100 },
  { title: '姓名', dataIndex: 'userName', width: 100 },
  { title: '入职日期', dataIndex: 'entryTime', width: 100 },
  { title: '离职日期', dataIndex: 'quitTime', width: 100 },
  { title: '服务期限', dataIndex: 'serviceTime', width: 100 },
  { title: '年度', dataIndex: 'computeYear', width: 50 },
  { title: '月份', dataIndex: 'computeMonth', width: 50 },
  { title: '社保起缴年度', dataIndex: 'insuranceStartYear', width: 50 },
  { title: '社保起缴月份', dataIndex: 'insuranceStartMonth', width: 50 },
  { title: '公积金起缴年度', dataIndex: 'housefundStartYear', width: 50 },
  { title: '公积金起缴月份', dataIndex: 'housefundStartMonth', width: 50 },
  { title: '社保停缴年度', dataIndex: 'insuranceShutYear', width: 50 },
  { title: '社保停缴月份', dataIndex: 'insuranceShutMonth', width: 50 },
  { title: '公积金停缴年度', dataIndex: 'housefundShutYear', width: 50 },
  { title: '公积金停缴月份', dataIndex: 'housefundShutMonth', width: 50 },
  { title: '参保城市', dataIndex: 'icName', width: 50 },
  { title: '参保标准', dataIndex: 'standardName', width: 50 },
  { title: '缴费规则', dataIndex: 'rulePay', width: 50 },
  { title: '缴费截止时间', dataIndex: 'ruleTime', width: 100 },
  { title: '养老险基数', dataIndex: 'pension', width: 100 },
  { title: '养老险-个人', dataIndex: 'pensionIndividual', width: 100 },
  { title: '养老险-公司', dataIndex: 'pensionCompany', width: 100 },
  { title: '养老金补缴-个人', dataIndex: 'pensionIndividualSupplement', width: 100 },
  { title: '养老金补缴-公司', dataIndex: 'pensionCompanySupplement', width: 100 },
  { title: '医疗险基数', dataIndex: 'medical', width: 100 },
  { title: '医疗险-个人', dataIndex: 'medicalIndividual', width: 100 },
  { title: '医疗险-公司', dataIndex: 'medicalCompany', width: 100 },
  { title: '医疗险补缴-个人', dataIndex: 'medicalIndividualSupplement', width: 100 },
  { title: '医疗险补缴-公司', dataIndex: 'medicalCompanySupplement', width: 100 },
  { title: '失业险基数', dataIndex: 'unemployment', width: 100 },
  { title: '失业险-个人', dataIndex: 'unemploymentIndividual', width: 100 },
  { title: '失业险-公司', dataIndex: 'unemploymentCompany', width: 100 },
  { title: '失业险补缴-个人', dataIndex: 'unemploymentIndividualSupplement', width: 100 },
  { title: '失业险补缴-公司', dataIndex: 'unemploymentCompanySupplement', width: 100 },
  { title: '生育险基数', dataIndex: 'fertility', width: 100 },
  { title: '生育险-个人', dataIndex: 'fertilityIndividual', width: 100 },
  { title: '生育险-公司', dataIndex: 'fertilityCompany', width: 100 },
  { title: '生育险补缴-个人', dataIndex: 'fertilityIndividualSupplement', width: 100 },
  { title: '生育险补缴-公司', dataIndex: 'fertilityCompanySupplement', width: 100 },
  { title: '工伤险基数', dataIndex: 'workhurt', width: 100 },
  { title: '工伤险-个人', dataIndex: 'workhurtIndividual', width: 100 },
  { title: '工伤险-公司', dataIndex: 'workhurtCompany', width: 100 },
  { title: '工伤险补缴-个人', dataIndex: 'workhurtIndividualSupplement', width: 100 },
  { title: '工伤险补缴-公司', dataIndex: 'workhurtCompanySupplement', width: 100 },
  { title: '补充医疗险基数', dataIndex: 'supMedical', width: 100 },
  { title: '补充医疗险-个人', dataIndex: 'supMedicalIndividual', width: 100 },
  { title: '补充医疗险-公司', dataIndex: 'supMedicalCompany', width: 100 },
  { title: '补充医疗险补缴-个人', dataIndex: 'supMedicalIndividualSupplement', width: 100 },
  { title: '补充医疗险补缴-公司', dataIndex: 'supMedicalCompanySupplement', width: 100 },
  { title: '大病医疗险基数', dataIndex: 'bigMedical', width: 100 },
  { title: '大病医疗险-个人', dataIndex: 'bigMedicalIndividual', width: 100 },
  { title: '大病医疗险-公司', dataIndex: 'bigMedicalCompany', width: 100 },
  { title: '大病医疗险补缴-个人', dataIndex: 'bigMedicalIndividualSupplement', width: 100 },
  { title: '大病医疗险补缴-公司', dataIndex: 'bigMedicalCompanySupplement', width: 100 },
  { title: '公积金基数', dataIndex: 'accFund', width: 100 },
  { title: '公积金-个人', dataIndex: 'accFundIndividual', width: 100 },
  { title: '公积金-公司', dataIndex: 'accFundCompany', width: 100 },
  { title: '公积金补缴-个人', dataIndex: 'accFundIndividualSupplement', width: 100 },
  { title: '公积金补缴-公司', dataIndex: 'accFundCompanySupplement', width: 100 },
  { title: '残保金', dataIndex: 'residualPremium', width: 100 },
  { title: '残保金补缴', dataIndex: 'residualPremiumSupplement', width: 100 },
  { title: '服务费', dataIndex: 'serve', width: 100 },
  { title: '服务费补缴', dataIndex: 'serveSupplement', width: 100 },
  { title: '补充公积金基数', dataIndex: 'supAccFund', width: 100 },
  { title: '补充公积金-个人', dataIndex: 'supAccFundIndividual', width: 100 },
  { title: '补充公积金-公司', dataIndex: 'supAccFundCompany', width: 100 },
  { title: '补充公积金补缴-个人', dataIndex: 'supAccFundIndividualSupplement', width: 100 },
  { title: '补充公积金补缴-公司', dataIndex: 'supAccFundCompanySupplement', width: 100 },
  { title: '社保-个人小计', dataIndex: 'insuranceIndividualSubtotal', width: 100 },
  { title: '社保补缴-个人小计', dataIndex: 'insuranceSupplementIndividualSubtotal', width: 100 },
  { title: '社保-公司小计', dataIndex: 'insuranceCompanySubtotal', width: 100 },
  { title: '社保补缴-公司小计', dataIndex: 'insuranceSupplementCompanySubtotal', width: 100 },
  { title: '社保-个人合计', dataIndex: 'insuranceIndividualTotal', width: 100 },
  { title: '社保补缴-公司合计', dataIndex: 'insuranceCompanyTotal', width: 100 },
  { title: '公积金-个人合计', dataIndex: 'accFundIndividualTotal', width: 100 },
  { title: '公积金-公司合计', dataIndex: 'accFundCompanyTotal', width: 100 },
  { title: '社保-个人公司总计', dataIndex: 'insuranceIndividualCompanyTotal', width: 100 },
  { title: '公积金-个人公司总计', dataIndex: 'accFundIndividualCompanyTotal', width: 100 },
  { title: '残保金-总计', dataIndex: 'residualPremiumTotal', width: 100 },
  { title: '服务费-总计', dataIndex: 'serveTotal', width: 100 }
]

// 09-参保费用拆分汇总表
const insuredCostColumns = [
  { title: '', dataIndex: 'index', width: 50 },
  { title: '项目', dataIndex: 'projectName', width: 50 },
  { title: '法人主体', dataIndex: 'entity', width: 150 },
  { title: '核算年', dataIndex: 'computeYear', width: 50 },
  { title: '核算月', dataIndex: 'computeMonth', width: 50 },
  { title: '社保参保人数', dataIndex: 'insuranceInsuredCount', width: 100 },
  { title: '养老险-基数汇总', dataIndex: 'pensionTotal', width: 100 },
  { title: '养老险-个人汇总', dataIndex: 'pensionIndividualTotal', width: 100 },
  { title: '养老险-公司汇总', dataIndex: 'pensionCompanyTotal', width: 100 },
  { title: '医疗险-基数汇总', dataIndex: 'medicalTotal', width: 100 },
  { title: '医疗险-个人汇总', dataIndex: 'medicalIndividualTotal', width: 100 },
  { title: '医疗险-公司汇总', dataIndex: 'medicalCompanyTotal', width: 100 },
  { title: '失业险-基数汇总', dataIndex: 'unemploymentTotal', width: 100 },
  { title: '失业险-个人汇总', dataIndex: 'unemploymentIndividualTotal', width: 100 },
  { title: '失业险-公司汇总', dataIndex: 'unemploymentCompanyTotal', width: 100 },
  { title: '生育险-基数汇总', dataIndex: 'fertilityTotal', width: 100 },
  { title: '生育险-个人汇总', dataIndex: 'fertilityIndividualTotal', width: 100 },
  { title: '生育险-公司汇总', dataIndex: 'fertilityCompanyTotal', width: 100 },
  { title: '工伤险-基数汇总', dataIndex: 'workhurtTotal', width: 100 },
  { title: '工伤险-个人汇总', dataIndex: 'workhurtIndividualTotal', width: 100 },
  { title: '工伤险-公司汇总', dataIndex: 'workhurtCompanyTotal', width: 100 },
  { title: '大病医疗险-基数汇总', dataIndex: 'bigMedicalTotal', width: 100 },
  { title: '大病医疗险-个人汇总', dataIndex: 'bigMedicalIndividualTotal', width: 100 },
  { title: '大病医疗险-公司汇总', dataIndex: 'bigMedicalCompanyTotal', width: 100 },
  { title: '补充医疗险-基数汇总', dataIndex: 'supMedicalTotal', width: 100 },
  { title: '补充医疗险-个人汇总', dataIndex: 'supMedicalIndividualTotal', width: 100 },
  { title: '补充医疗险-公司汇总', dataIndex: 'supMedicalCompanyTotal', width: 100 },
  { title: '公积金参保人数', dataIndex: 'accFundInsuredCount', width: 100 },
  { title: '公积金-基数汇总', dataIndex: 'accFundTotal', width: 100 },
  { title: '公积金-个人汇总', dataIndex: 'accFundIndividualTotal', width: 100 },
  { title: '公积金-公司汇总', dataIndex: 'accFundCompanyTotal', width: 100 },
  { title: '补充公积金-基数汇总', dataIndex: 'supAccFundTotal', width: 100 },
  { title: '补充公积金-个人汇总', dataIndex: 'supAccFundIndividualTotal', width: 100 },
  { title: '补充公积金-公司汇总', dataIndex: 'supAccFundCompanyTotal', width: 100 },
  { title: '残保金参保人数', dataIndex: 'residualPremiumInsuredCount', width: 100 },
  { title: '残保金-公司汇总', dataIndex: 'residualPremiumCompanyCount', width: 100 },
  { title: '服务费-公司汇总', dataIndex: 'serveCount', width: 100 }
]

// 10-参保费用付款汇总表
const insuredPayColumns = [
  { title: '', dataIndex: 'index', width: 50 },
  { title: '项目', dataIndex: 'projectName', width: 50 },
  { title: '法人主体', dataIndex: 'entity', width: 150 },
  { title: '组织', dataIndex: 'organize', width: 100 },
  { title: '核算年', dataIndex: 'computeYear', width: 50 },
  { title: '核算月', dataIndex: 'computeMonth', width: 50 },
  { title: '社保费用-职工薪酬', dataIndex: 'insuranceCostEmolument', width: 100 },
  { title: '社保费用-公司', dataIndex: 'insuranceCostCompany', width: 100 },
  { title: '公积金费用-职工薪酬', dataIndex: 'accFundCostEmolument', width: 100 },
  { title: '公积金费用-公司', dataIndex: 'accFundCostCompany', width: 100 },
  { title: '残保金费用-公司', dataIndex: 'residualPremiumCostCompany', width: 100 },
  { title: '服务费用-公司', dataIndex: 'serveCostCompany', width: 100 }
]

export {
  reportFormTemplateList,
  rosterColumns,
  workingColumns,
  quitColumns,
  probationPeriod,
  contractEndColumns,
  contractInfoColumns,
  jobChangeColumns,
  insuredDetailColumns,
  insuredCostColumns,
  insuredPayColumns
}
